version: "3.9"

services:
  
  backend:
    build: ./backend
    container_name: seedling-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env     # loads env from project root
    networks:
      - seedling-net

  frontend:
    build: ./frontend
    container_name: seedling-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      BACKEND_URL: "http://backend:8000"   # internal DNS hostname
    networks:
      - seedling-net

networks:
  seedling-net:
    driver: bridge
