services:
  backend:
    build: ./backend
    container_name: seedling-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "9000:8000"

  frontend:
    build: ./frontend
    container_name: seedling-frontend
    restart: always
    depends_on:
      - backend
    environment:
      BACKEND_URL: "http://backend:8000"
    ports:
      - "8501:8501"
